// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmpjZklbqcfHKWYY9-MZ2Nd7TB0LovT04',
    appId: '1:142359706639:web:6df5a0bbc9ebc6c7ccf77a',
    messagingSenderId: '142359706639',
    projectId: 'prime-pos-system',
    authDomain: 'prime-pos-system.firebaseapp.com',
    storageBucket: 'prime-pos-system.appspot.com',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmpjZklbqcfHKWYY9-MZ2Nd7TB0LovT04',
    appId: '1:142359706639:android:6df5a0bbc9ebc6c7ccf77a',
    messagingSenderId: '142359706639',
    projectId: 'prime-pos-system',
    storageBucket: 'prime-pos-system.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmpjZklbqcfHKWYY9-MZ2Nd7TB0LovT04',
    appId: '1:142359706639:ios:6df5a0bbc9ebc6c7ccf77a',
    messagingSenderId: '142359706639',
    projectId: 'prime-pos-system',
    storageBucket: 'prime-pos-system.appspot.com',
    iosBundleId: 'com.primepos.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmpjZklbqcfHKWYY9-MZ2Nd7TB0LovT04',
    appId: '1:142359706639:ios:6df5a0bbc9ebc6c7ccf77a',
    messagingSenderId: '142359706639',
    projectId: 'prime-pos-system',
    storageBucket: 'prime-pos-system.appspot.com',
    iosBundleId: 'com.primepos.app',
  );
}
